# Generated by Django 5.0.6 on 2024-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_post_body_post_post_image_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='static/images/blog_post'),
        ),
    ]
